plugins {
    id 'java-library'
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

dependencies {
    api project(':core:virtual-controls')
    implementation 'com.google.code.gson:gson:2.14.0'

    testImplementation 'junit:junit:4.13.2'
}
